# Generated by Django 4.1.7 on 2023-04-01 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administer',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('Password', models.CharField(max_length=250, verbose_name='密码')),
                ('Email', models.CharField(max_length=250, unique=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '管理员信息表',
                'db_table': 'administer',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('Time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('Text', models.CharField(max_length=250, verbose_name='内容')),
                ('Images', models.CharField(default='', max_length=250, verbose_name='图片')),
            ],
            options={
                'verbose_name': '评论信息表',
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('Time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('Title', models.CharField(max_length=250, verbose_name='标题')),
                ('Text', models.CharField(max_length=250, verbose_name='内容')),
                ('Images', models.CharField(default='', max_length=250, verbose_name='图片')),
            ],
            options={
                'verbose_name': '帖子信息表',
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('Title', models.CharField(max_length=250, verbose_name='标题')),
                ('Time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('Text', models.CharField(max_length=250, verbose_name='内容')),
                ('Capacity', models.IntegerField(default=0, verbose_name='人数')),
                ('Tutor', models.CharField(max_length=250, verbose_name='导师姓名')),
                ('Place', models.CharField(max_length=250, verbose_name='单位')),
                ('Duration', models.CharField(max_length=250, verbose_name='持续时间')),
                ('Type', models.CharField(max_length=250, verbose_name='线上/线下')),
                ('State', models.CharField(max_length=250, verbose_name='项目状态')),
            ],
            options={
                'verbose_name': '项目信息表',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('Name', models.CharField(max_length=250, verbose_name='姓名')),
                ('School', models.CharField(max_length=250, verbose_name='学校')),
                ('Email', models.CharField(max_length=250, unique=True, verbose_name='邮箱')),
                ('Password', models.CharField(max_length=250, verbose_name='密码')),
                ('Majority', models.CharField(max_length=250, verbose_name='专业方向')),
                ('Rewards', models.TextField(null=True, verbose_name='竞赛获奖')),
                ('SchoolScores', models.CharField(max_length=250, null=True, verbose_name='学习成绩')),
                ('Skills', models.TextField(null=True, verbose_name='技术栈')),
                ('ScientificExperience', models.TextField(null=True, verbose_name='科研经历')),
                ('EnterpriseCertification', models.BooleanField(default=False, verbose_name='企业认证')),
                ('CV', models.CharField(default='', max_length=250, verbose_name='简历')),
            ],
            options={
                'verbose_name': '学生信息表',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('Name', models.CharField(max_length=250, verbose_name='姓名')),
                ('School', models.CharField(max_length=250, verbose_name='学校')),
                ('Email', models.CharField(max_length=250, unique=True, verbose_name='邮箱')),
                ('Password', models.CharField(max_length=250, verbose_name='密码')),
                ('Majority', models.CharField(max_length=250, verbose_name='专业方向')),
                ('Position', models.CharField(max_length=250, null=True, verbose_name='职称')),
                ('EductionExperience', models.TextField(null=True, verbose_name='教育经历')),
                ('Paper', models.CharField(max_length=250, null=True, verbose_name='论文发表')),
            ],
            options={
                'verbose_name': '导师信息表',
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('Direction', models.CharField(max_length=250, verbose_name='发送方向')),
                ('Time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('Text', models.CharField(max_length=250, verbose_name='内容')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.student', verbose_name='学生ID')),
                ('TutTutorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.tutor', verbose_name='导师ID')),
            ],
            options={
                'verbose_name': '发送消息',
                'db_table': 'SendMessage',
            },
        ),
        migrations.CreateModel(
            name='SelectProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(default='', max_length=250)),
                ('PlatScore', models.FloatField(default=0)),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.project', verbose_name='项目ID')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.student', verbose_name='学生ID')),
            ],
            options={
                'verbose_name': '学生选择项目',
                'db_table': 'selectproject',
                'unique_together': {('StudentID', 'ProjectID')},
            },
        ),
        migrations.CreateModel(
            name='PublishPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.post', verbose_name='帖子ID')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.student', verbose_name='学生ID')),
            ],
            options={
                'verbose_name': '学生发帖',
                'db_table': 'PublishPost',
                'unique_together': {('StudentID', 'PostID')},
            },
        ),
        migrations.CreateModel(
            name='MakeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.comment', verbose_name='评论ID')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.student', verbose_name='学生ID')),
            ],
            options={
                'verbose_name': '发表评论',
                'db_table': 'MakeComment',
                'unique_together': {('StudentID', 'CommentID')},
            },
        ),
        migrations.CreateModel(
            name='CreateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlatScore', models.FloatField(default=0)),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.project', verbose_name='项目ID')),
                ('TutorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.tutor', verbose_name='导师ID')),
            ],
            options={
                'verbose_name': '导师创建项目',
                'db_table': 'createproject',
                'unique_together': {('TutorID', 'ProjectID')},
            },
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.comment', verbose_name='评论ID')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.post', verbose_name='帖子ID')),
            ],
            options={
                'verbose_name': '评论帖子',
                'db_table': 'CommentPost',
                'unique_together': {('PostID', 'CommentID')},
            },
        ),
        migrations.CreateModel(
            name='CollectProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.project', verbose_name='项目ID')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.student', verbose_name='学生ID')),
            ],
            options={
                'verbose_name': '收藏项目',
                'db_table': 'CollectProject',
                'unique_together': {('StudentID', 'ProjectID')},
            },
        ),
        migrations.CreateModel(
            name='CollectPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.post', verbose_name='帖子ID')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.student', verbose_name='学生ID')),
            ],
            options={
                'verbose_name': '收藏帖子',
                'db_table': 'CollectPost',
                'unique_together': {('StudentID', 'PostID')},
            },
        ),
    ]
