# Generated by Django 4.1.7 on 2023-03-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='belonglab',
            unique_together=set(),
        ),
    ]
